Add&remove
ZahraArshia/To-Do-List pull request #2
Opened 2022-02-23 20:20 UTC by ZahraArshia

Hello 😊 
## in this step of project:
- a new JavaScript file is added with the name of CRUD.js including class "Task" with methods for add, remove, edit and update
- index key of each task is updating according to its position in storage array
- edit function don't affect the position of the item in list, just changes the description
## in the feature:
the `clear all completed` button is disable for now, in next step its functionality will be implemented due to Microverse schedule

2022-02-23 21:06 UTC, micheaol requested changes
Hi @ZahraArshia , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-23 21:06 UTC, micheaol commented on src/CRUD.js
> +  }
Please ensure that `items` are numbered from ` 1 ` according to the project requirement and NOT ` 0 `.
![image](https://user-images.githubusercontent.com/10332499/155408148-57373098-b3c5-4ed1-8e2b-b2600dc36fab.png).

2022-02-24 07:27 UTC, ZahraArshia commented
Hello;
the indexes are starting from 1 now 😊

2022-02-24 07:39 UTC, Rustamxon7 approved these changes
## Hi @ZahraArshia   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-24 07:43 UTC, merged